'use client'

import { useEffect, useState, useRef, useCallback } from 'react'
import { useAuth } from '@/contexts/AuthContext'
import { createClient } from '@/lib/supabase/client'
import { formatRelativeTime, formatDuration } from '@/lib/utils/format'
import LoadingSpinner from '@/components/dashboard/LoadingSpinner'
import EmptyState from '@/components/dashboard/EmptyState'

interface Recording {
  id: string
  user_id: string
  title: string
  duration: number
  file_path: string
  transcription: string | null
  created_at: string
}

export default function RecordingsPage() {
  const { user } = useAuth()
  const [recordings, setRecordings] = useState<Recording[]>([])
  const [loading, setLoading] = useState(true)
  const [recording, setRecording] = useState(false)
  const [recordingTime, setRecordingTime] = useState(0)
  const [showTitleModal, setShowTitleModal] = useState(false)
  const [newRecordingTitle, setNewRecordingTitle] = useState('')
  const [pendingRecording, setPendingRecording] = useState<Blob | null>(null)
  const [selectedRecording, setSelectedRecording] = useState<Recording | null>(null)
  const [transcribing, setTranscribing] = useState(false)
  
  const mediaRecorderRef = useRef<MediaRecorder | null>(null)
  const audioChunksRef = useRef<Blob[]>([])
  const timerRef = useRef<NodeJS.Timeout | null>(null)
  const supabase = createClient()

  const fetchRecordings = useCallback(async () => {
    if (!user) return

    setLoading(true)
    try {
      const { data, error } = await supabase
        .from('diffuse_recordings')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })

      if (error) throw error
      setRecordings(data || [])
    } catch (error) {
      console.error('Error fetching recordings:', error)
    } finally {
      setLoading(false)
    }
  }, [user, supabase])

  useEffect(() => {
    fetchRecordings()
  }, [fetchRecordings])

  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
      const mediaRecorder = new MediaRecorder(stream)
      mediaRecorderRef.current = mediaRecorder
      audioChunksRef.current = []

      mediaRecorder.ondataavailable = (event) => {
        audioChunksRef.current.push(event.data)
      }

      mediaRecorder.onstop = () => {
        const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' })
        setPendingRecording(audioBlob)
        setShowTitleModal(true)
        stream.getTracks().forEach(track => track.stop())
      }

      mediaRecorder.start()
      setRecording(true)
      setRecordingTime(0)

      // Start timer
      timerRef.current = setInterval(() => {
        setRecordingTime((prev) => prev + 1)
      }, 1000)
    } catch (error) {
      console.error('Error starting recording:', error)
      alert('Failed to access microphone. Please check permissions.')
    }
  }

  const stopRecording = () => {
    if (mediaRecorderRef.current && recording) {
      mediaRecorderRef.current.stop()
      setRecording(false)
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }

  const saveRecording = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!pendingRecording || !user) return

    setLoading(true)
    try {
      // Upload to Supabase Storage
      const fileName = `${user.id}/${Date.now()}.webm`
      const { error: uploadError } = await supabase.storage
        .from('recordings')
        .upload(fileName, pendingRecording)

      if (uploadError) throw uploadError

      // Save metadata to database
      const { error: dbError } = await supabase
        .from('diffuse_recordings')
        .insert({
          user_id: user.id,
          title: newRecordingTitle,
          duration: recordingTime,
          file_path: fileName,
        })

      if (dbError) throw dbError

      setNewRecordingTitle('')
      setShowTitleModal(false)
      setPendingRecording(null)
      setRecordingTime(0)
      fetchRecordings()
    } catch (error) {
      console.error('Error saving recording:', error)
      alert('Failed to save recording')
    } finally {
      setLoading(false)
    }
  }

  const transcribeRecording = async (recording: Recording) => {
    setTranscribing(true)
    setSelectedRecording(recording)

    try {
      // In a real app, you'd call a transcription API (e.g., OpenAI Whisper, Deepgram)
      // For now, we'll simulate it
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      const mockTranscription = "This is a sample transcription of the audio recording. In a real implementation, this would be generated by a speech-to-text API service."

      const { error } = await supabase
        .from('diffuse_recordings')
        .update({ transcription: mockTranscription })
        .eq('id', recording.id)

      if (error) throw error

      fetchRecordings()
      setSelectedRecording({ ...recording, transcription: mockTranscription })
    } catch (error) {
      console.error('Error transcribing:', error)
      alert('Failed to transcribe recording')
    } finally {
      setTranscribing(false)
    }
  }

  const deleteRecording = async (id: string, filePath: string) => {
    if (!confirm('Are you sure you want to delete this recording?')) return

    try {
      // Delete from storage
      await supabase.storage.from('recordings').remove([filePath])

      // Delete from database
      const { error } = await supabase
        .from('diffuse_recordings')
        .delete()
        .eq('id', id)

      if (error) throw error

      fetchRecordings()
    } catch (error) {
      console.error('Error deleting recording:', error)
      alert('Failed to delete recording')
    }
  }

  if (!user) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <LoadingSpinner size="lg" />
      </div>
    )
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-display-sm text-secondary-white">Recordings</h1>
        
        {/* Recording Controls */}
        {!recording ? (
          <button
            onClick={startRecording}
            className="btn-primary px-6 py-3 flex items-center gap-2"
          >
            <span className="text-xl">🎙️</span>
            Start Recording
          </button>
        ) : (
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="animate-pulse w-3 h-3 bg-red-500 rounded-full"></span>
              <span className="text-body-md text-secondary-white">
                {Math.floor(recordingTime / 60)}:{(recordingTime % 60).toString().padStart(2, '0')}
              </span>
            </div>
            <button
              onClick={stopRecording}
              className="btn-primary px-6 py-3 bg-red-500 hover:bg-red-600"
            >
              Stop Recording
            </button>
          </div>
        )}
      </div>

      {/* Recordings List */}
      {loading ? (
        <div className="flex items-center justify-center py-16">
          <LoadingSpinner size="lg" />
        </div>
      ) : recordings.length === 0 ? (
        <EmptyState
          icon={<span className="text-6xl">🎙️</span>}
          title="No Recordings Yet"
          description="Start recording audio to create transcriptions for your projects."
          action={{
            label: 'Start Recording',
            onClick: startRecording,
          }}
        />
      ) : (
        <div className="space-y-4">
          {recordings.map((recording) => (
            <div
              key={recording.id}
              className="glass-container p-6 hover:bg-white/5 transition-colors"
            >
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <h3 className="text-heading-md text-secondary-white mb-2">
                    {recording.title}
                  </h3>
                  <p className="text-body-sm text-medium-gray mb-3">
                    {formatDuration(recording.duration)} • {formatRelativeTime(recording.created_at)}
                  </p>
                  
                  {recording.transcription && (
                    <div className="mt-4 p-4 bg-white/5 rounded-glass">
                      <p className="text-body-sm text-secondary-white whitespace-pre-wrap">
                        {recording.transcription}
                      </p>
                    </div>
                  )}
                </div>

                <div className="flex gap-2 ml-4">
                  {!recording.transcription ? (
                    <button
                      onClick={() => transcribeRecording(recording)}
                      disabled={transcribing}
                      className="btn-secondary px-4 py-2 text-body-sm disabled:opacity-50"
                    >
                      {transcribing && selectedRecording?.id === recording.id
                        ? 'Transcribing...'
                        : 'Transcribe'}
                    </button>
                  ) : (
                    <button
                      onClick={() => setSelectedRecording(recording)}
                      className="btn-secondary px-4 py-2 text-body-sm"
                    >
                      View
                    </button>
                  )}
                  <button
                    onClick={() => deleteRecording(recording.id, recording.file_path)}
                    className="btn-secondary px-4 py-2 text-body-sm text-red-400 hover:text-red-300"
                  >
                    Delete
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Title Modal */}
      {showTitleModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="glass-container p-8 max-w-md w-full">
            <h2 className="text-heading-lg text-secondary-white mb-6">Save Recording</h2>
            <form onSubmit={saveRecording} className="space-y-4">
              <div>
                <label className="block text-body-sm text-secondary-white mb-2">
                  Title
                </label>
                <input
                  type="text"
                  value={newRecordingTitle}
                  onChange={(e) => setNewRecordingTitle(e.target.value)}
                  placeholder="Town Council Meeting - Jan 2026"
                  required
                  className="w-full px-4 py-3 bg-white/5 border border-white/10 rounded-glass text-secondary-white text-body-md focus:outline-none focus:border-cosmic-orange transition-colors"
                />
              </div>
              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => {
                    setShowTitleModal(false)
                    setPendingRecording(null)
                  }}
                  className="btn-secondary flex-1 py-3"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="btn-primary flex-1 py-3 disabled:opacity-50"
                >
                  {loading ? 'Saving...' : 'Save'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Transcription Modal */}
      {selectedRecording && selectedRecording.transcription && !transcribing && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="glass-container p-8 max-w-2xl w-full max-h-[80vh] overflow-y-auto">
            <div className="flex items-start justify-between mb-6">
              <h2 className="text-heading-lg text-secondary-white">
                {selectedRecording.title}
              </h2>
              <button
                onClick={() => setSelectedRecording(null)}
                className="text-medium-gray hover:text-secondary-white transition-colors"
              >
                ✕
              </button>
            </div>
            <div className="mb-4">
              <p className="text-body-sm text-medium-gray">
                {formatDuration(selectedRecording.duration)} • {formatRelativeTime(selectedRecording.created_at)}
              </p>
            </div>
            <div className="p-4 bg-white/5 rounded-glass">
              <p className="text-body-md text-secondary-white whitespace-pre-wrap leading-relaxed">
                {selectedRecording.transcription}
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

